abbr sf "source ~/.config/fish/config.fish"
abbr st "tmux source ~/.config/tmux/tmux.conf"
abbr ta "tmux a"
abbr tat "tmux attach -t"
# abbr td "t dotfiles"
# abbr td "t ~/.local/share/chezmoi"
abbr tk "tmux kill-server"
abbr tr "tldr --list | fzf --header 'tldr (tealdeer)' --reverse --preview 'tldr {1} --color=always' --preview-window=right,80% | xargs tldr"
abbr tn "tmux new -s (basename (pwd))"
abbr vf "chezmoi edit ~/.config/fish/config.fish"
abbr vk "chezmoi edit ~/.config/kitty/kitty.conf"
abbr vt "chezmoi edit ~/.config/tmux/tmux.conf"
abbr vp "nvim package.json"
abbr vpc "nvim +PlugClean"
abbr vpi "nvim +PlugInstall"
abbr vpu "nvim +PlugUpdate"
abbr vpug "nvim +PlugUpgrade"
abbr vt "chezmoi edit ~/.config/tmux/tmux.conf"
