abbr bb "brew bundle --file=~/Brewfile"
abbr gg lazygit
abbr ls exa
abbr sf "source ~/.config/fish/config.fish"
abbr sfa "source ~/.config/fish/conf.d/abbr.fish"
abbr st "tmux source ~/.config/tmux/tmux.conf"
abbr ta "tmux a"
abbr tat "tmux attach -t"
# abbr td "t dotfiles"
abbr td "t ~/.local/share/chezmoi"
abbr tk "tmux kill-server"
abbr tr "tldr --list | fzf --header 'tldr (tealdeer)' --reverse --preview 'tldr {1}' --preview-window=right,80% | xargs tldr"
abbr tn "tmux new -s (basename (pwd))"
abbr va "chezmoi edit --apply ~/.config/fish/conf.d/abbr.fish"
abbr vb "chezmoi edit --apply ~/Brewfile"
abbr vf "chezmoi edit --apply ~/.config/fish/config.fish"
abbr vk "chezmoi edit --apply ~/.config/kitty/kitty.conf"
abbr vt "chezmoi edit --apply ~/.config/tmux/tmux.conf"
abbr vp "nvim package.json"
abbr vpc "nvim +PlugClean"
abbr vpi "nvim +PlugInstall"
abbr vpu "nvim +PlugUpdate"
abbr vpug "nvim +PlugUpgrade"
