abbr bb "brew bundle install --cleanup"
abbr gg lazygit
abbr ls exa
abbr sfa "source ~/.config/fish/conf.d/abbr.fish"
abbr sfc "source ~/.config/fish/config.fish"
abbr st "tmux source ~/.config/tmux/tmux.conf"
abbr ta "tmux a"
abbr tat "tmux attach -t"
abbr td "t ~/.local/share/chezmoi"
abbr tk "tmux kill-server"
abbr tn "tmux new -s (basename (pwd))"
abbr tldr "tldr --list | fzf --header 'tldr (tealdeer)' --reverse --preview 'tldr {1}' --preview-window=right,80% | xargs tldr"
abbr vb "chezmoi edit --apply ~/Brewfile"
abbr vfa "chezmoi edit --apply ~/.config/fish/conf.d/abbr.fish"
abbr vfc "chezmoi edit --apply ~/.config/fish/config.fish"
abbr vk "chezmoi edit --apply ~/.config/kitty/kitty.conf"
abbr vt "chezmoi edit --apply ~/.config/tmux/tmux.conf"
