tap "1password/tap"
tap "charmbracelet/tap"
tap "cormacrelf/tap"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "oven-sh/bun"

brew "ansible"
brew "atuin"
brew "azure-cli"
brew "bat"
brew "bun"
brew "btop"
brew "cask"
brew "charmbracelet/tap/charm"
brew "charmbracelet/tap/glow"
brew "charmbracelet/tap/mods"
brew "charmbracelet/tap/skate"
brew "chezmoi"
brew "cmake"
brew "cmark-gfm"
brew "cormacrelf/tap/dark-notify"
brew "delve"
brew "diff-pdf"
brew "diffutils"
brew "elm"
brew "eza"
brew "exercism"
brew "fd"
brew "fish"
brew "flyctl"
brew "fzf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnupg"
brew "go"
brew "go-task"
brew "golangci-lint"
brew "goreleaser/tap/goreleaser"
brew "gum"
brew "grc"
brew "helix"
brew "hugo"
brew "jq"
brew "lazygit"
brew "lf"
brew "luajit-openresty"
brew "luarocks"
brew "mas"
brew "mdbook"
brew "mosh"
brew "ncdu"
brew "neofetch"
brew "neovim"
brew "netlify-cli"
brew "node"
brew "opam"
brew "pandoc"
brew "pngpaste"
brew "pre-commit"
brew "poppler"
brew "python"
brew "rename"
brew "ripgrep"
brew "ruby"
brew "slides"
brew "speedtest-cli"
brew "sqlite"
brew "starship"
brew "subversion"
brew "terminator"
brew "thefuck"
brew "tldr"
brew "tmux"
brew "tmuxinator"
brew "typescript"
brew "wget"
brew "yt-dlp"
brew "zoxide"

cask "1password" 
cask "1password-cli" 
cask "alfred" 
cask "basictex"
cask "bbedit"
cask "cheatsheet"
cask "chrysalis"
cask "customshortcuts"
cask "devonthink"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "fleet"
cask "fluor"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-input"
cask "font-jetbrains-mono-nerd-font"
cask "font-monoid-nerd-font"
cask "github"
cask "goland"
cask "grammarly"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keyboard-maestro"
cask "keyboardcleantool"
cask "keycastr"
cask "kitty"
cask "microsoft-edge"
cask "moom"
cask "nordvpn"
cask "obsidian"
cask "openinterminal"
cask "rider"
cask "setapp"
cask "textexpander"
cask "visual-studio-code"
cask "vlc"
cask "warp"
cask "wezterm"
cask "zed"
cask "zoom"

mas "Amphetamine", id: 937984704
mas "Cardhop", id: 1290358394
mas "Day One", id: 1055511498
mas "Dice", id: 1479250666
mas "Drafts", id: 1435957248
mas "DuckDuckGo Privacy for Safari", id: 1482920575
mas "Fantastical", id: 975937182
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Paprika Recipe Manager 3", id: 1303222628
mas "Parcel", id: 639968404
mas "Patterns", id: 429449079
mas "Reeder", id: 1529448980
mas "Save to Reader", id: 1640236961
mas "Super Agent", id: 1568262835
mas "URL Linker", id: 1289119450
mas "uBlacklist for Safari", id: 1547912640
